graph:
	dot -Tpdf docking-station.state.dot > docking-station.state.pdf
	dot -Tpdf employee.state.dot > employee.state.pdf
jpg:
	dot -Tjpg docking-station.state.dot > docking-station.state.jpg
	dot -Tjpg employee.state.dot > employee.state.jpg
